## Exercices Numpy

### 1

Créez un array avec les entiers 0 à 10 et générez en sortie un array où les valeurs
impaires de l'array ont été remplacées par des -1.

Sortie désirée : array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [12]:
import numpy as np

a = np.arange(10)
a[a % 2 == 1] = -1  

print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 2

Créez un array avec les entiers de 0 à 100 et générez en sortie un array contenant
seulement les nombres premiers.

Aide: commencez par créer une fonction qui calcule si un nombre entier est un nombre
premier (c.a.d., qu’il n'est pas divisible par 2,3,4,5.... ni par sqrt(n), où n est le nombre
testé).

In [77]:
import numpy as np

def isPrime(n):
    if(n < 2): return False
    for x in range(2, (int)(np.sqrt(n)) + 1):
        if n % x == 0:
            return False
    return True

a = np.arange(100)
prime = [i for i in a if isPrime(i)]

print(prime)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### 3

Soit la matrice donnée ci-dessous, calculez la somme des éléments de chaque ligne et
de chaque colonne en utilisant la méthode numpy.sum()

MS = [[20, 12, 4, 45, 37, 29, 28], [11, 3, 44, 36, 35, 27, 19], [2, 43, 42, 34, 26, 18, 10],
[49, 41, 33, 25, 17, 9, 1], [40, 32, 24, 16, 8, 7, 48], [31, 23, 15, 14, 6, 47, 39], [22, 21, 13,
5, 46, 38, 30]]

In [70]:
import numpy as np

MS = np.array([
    [20, 12, 4, 45, 37, 29, 28],
    [11, 3, 44, 36, 35, 27, 19],
    [2, 43, 42, 34, 26, 18, 10],
    [49, 41, 33, 25, 17, 9, 1],
    [40, 32, 24, 16, 8, 7, 48],
    [31, 23, 15, 14, 6, 47, 39],
    [22, 21, 13, 5, 46, 38, 30]
])


print(MS.sum(axis=0))
print(MS.sum(axis=1))

[175 175 175 175 175 175 175]
[175 175 175 175 175 175 175]


### 4

Générez une matrice de dimensions 10x10 contenant des valeurs aléatoires entre -1.0
et 1.0. Calculez la valeur maximale, minimale et moyenne. Calculez la position où se
trouve la valeur maximale et minimale (argmax et argmin) et la position du minimum par
ligne (axis=1).

In [35]:
import numpy as np

matrix = np.random.uniform(-1.0, 1.0, (10, 10))

min = matrix.min()
posMin = matrix.argmin()

max = matrix.max()
posMax = matrix.argmax()

avg = matrix.mean()

minPerLine = matrix.min(axis=1)

print(f"Minimum: {min} at position {posMin}")
print(f"Maximum: {max} at position {posMax}")
print(f"Average: {avg}")
print(f"Min per line: {minPerLine}")
# print(matrix)

Minimum: -0.9847552971721352 at position 76
Maximum: 0.9929867065836104 at position 24
Average: 0.007970028802058686
Min per line: [-0.95586058 -0.63390562 -0.95883632 -0.90580681 -0.97794245 -0.91001776
 -0.83381417 -0.9847553  -0.7464368  -0.56909237]


### 5

Créez une matrice x de dimensions 10x10 contenant des valeurs aléatoires entre 0.0 et
1.0 et calculez le carré de chaque élément. Comparez le temps de calcul (p.ex. utilisez
la magic command %%timeit) d’une implémentation qui utilise une double boucle for et
une implémentation qui fait le calcul demandé tout simplement ainsi : x = x ** 2

In [75]:
import numpy as np

matrix = np.random.uniform(0.0, 1.0, (10, 10))

s1 = np.array(matrix)
print("** 2")
s1 = %timeit s1 ** 2

s2 = np.array(matrix)
def square(m):
    for i in range(len(m)):
        for j in range(len(m[i])):
            m[i][j] = m[i][j] ** 2
    return m

print("2 loops")
%timeit square(s2)


** 2
529 ns ± 1.29 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2 loops
55.9 µs ± 518 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 6

Créez un array de dimension 100 avec des valeurs aléatoires entre 0 et 1.0 et générez
un nouvel array où les éléments plus petits que 0.5 sont élevées au carré. Comparez le
temps de calcul a) d’une implémentation à l’aide d’une boucle for, b) d’une
implémentation qui utilise la méthode np.where(), et c) d’une implémentation à travers
des masques.

In [112]:
import numpy as np

array = np.random.uniform(0.0, 1.0, 100)
print(array)

# a) for loop
#a = [i ** 2 for i in a if i < 0.5]
def method_a():
    a = []
    for i in array:
        a.append(i ** 2 if i < 0.5 else i)
    return a

a = method_a()

print("a) ------------")
print(a)

# b) np.where()

# c) masks


[0.63329735 0.69091766 0.35400581 0.88574872 0.66649214 0.60638308
 0.95676983 0.94265847 0.48295685 0.63688855 0.34653444 0.9700986
 0.19195542 0.55037058 0.17804518 0.66872601 0.18161077 0.12100917
 0.17143092 0.52338758 0.3116651  0.54203264 0.45755811 0.65214437
 0.57554135 0.85214127 0.5339965  0.21377039 0.83665213 0.25303537
 0.06463022 0.43919051 0.60167436 0.83137129 0.53855227 0.99613218
 0.64135905 0.38123659 0.50138355 0.2728301  0.81236222 0.68532054
 0.51291236 0.46876582 0.77958007 0.71020368 0.63787085 0.49819655
 0.54417163 0.69481357 0.32703468 0.24716053 0.00342041 0.96083171
 0.15092257 0.7422127  0.96162417 0.66629181 0.59716267 0.70942728
 0.99881711 0.439283   0.88773372 0.91965181 0.70979048 0.61238021
 0.97191598 0.41610027 0.08030296 0.82778321 0.4448332  0.6519601
 0.76201459 0.8567396  0.92436313 0.80860359 0.73504642 0.75151197
 0.49722377 0.86394563 0.27176689 0.76492279 0.03660287 0.46264212
 0.4389698  0.18346023 0.12587761 0.25046423 0.69391341 0.013483

## Exercices Matplotlib

### 7

Générez un graphique de la fonction tangente hyperbolique définie par :

tanh(x) = (1 - exp(-2 * x)) / (1 + exp(-2 * x)), pour -5 < x < 5

Ajouter un titre, des labels et une grille