## Exercices Numpy

### 1

In [12]:
import numpy as np

a = np.arange(10)
a[a % 2 == 1] = -1  

print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 2

In [51]:
import numpy as np

def isPrime(n):
    if(n < 2): return False
    for x in range(2, (int)(np.sqrt(n)) + 1):
        if n % x == 0:
            return False
    return True

a = np.arange(100)
prime = [i for i in a if isPrime(i)]

print(a)
print(prime)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### 3

In [70]:
import numpy as np

MS = np.array([
    [20, 12, 4, 45, 37, 29, 28],
    [11, 3, 44, 36, 35, 27, 19],
    [2, 43, 42, 34, 26, 18, 10],
    [49, 41, 33, 25, 17, 9, 1],
    [40, 32, 24, 16, 8, 7, 48],
    [31, 23, 15, 14, 6, 47, 39],
    [22, 21, 13, 5, 46, 38, 30]
])


print(MS.sum(axis=0))
print(MS.sum(axis=1))

[175 175 175 175 175 175 175]
[175 175 175 175 175 175 175]


### 4

In [35]:
import numpy as np

matrix = np.random.uniform(-1.0, 1.0, (10, 10))

min = matrix.min()
posMin = matrix.argmin()

max = matrix.max()
posMax = matrix.argmax()

avg = matrix.mean()

minPerLine = matrix.min(axis=1)

print(f"Minimum: {min} at position {posMin}")
print(f"Maximum: {max} at position {posMax}")
print(f"Average: {avg}")
print(f"Min per line: {minPerLine}")
# print(matrix)

Minimum: -0.9847552971721352 at position 76
Maximum: 0.9929867065836104 at position 24
Average: 0.007970028802058686
Min per line: [-0.95586058 -0.63390562 -0.95883632 -0.90580681 -0.97794245 -0.91001776
 -0.83381417 -0.9847553  -0.7464368  -0.56909237]


### 5

In [75]:
import numpy as np

matrix = np.random.uniform(0.0, 1.0, (10, 10))

s1 = np.array(matrix)
print("** 2")
s1 = %timeit s1 ** 2

s2 = np.array(matrix)
def square(m):
    for i in range(len(m)):
        for j in range(len(m[i])):
            m[i][j] = m[i][j] ** 2
    return m

print("2 loops")
%timeit square(s2)


** 2
529 ns ± 1.29 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2 loops
55.9 µs ± 518 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 6