## Exercices Numpy

### 1

Créez un array avec les entiers 0 à 10 et générez en sortie un array où les valeurs
impaires de l'array ont été remplacées par des -1.

Sortie désirée : array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [12]:
import numpy as np

a = np.arange(10)
a[a % 2 == 1] = -1  

print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 2

Créez un array avec les entiers de 0 à 100 et générez en sortie un array contenant
seulement les nombres premiers.

Aide: commencez par créer une fonction qui calcule si un nombre entier est un nombre
premier (c.a.d., qu’il n'est pas divisible par 2,3,4,5.... ni par sqrt(n), où n est le nombre
testé).

In [77]:
import numpy as np

def isPrime(n):
    if(n < 2): return False
    for x in range(2, (int)(np.sqrt(n)) + 1):
        if n % x == 0:
            return False
    return True

a = np.arange(100)
prime = [i for i in a if isPrime(i)]

print(prime)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### 3

Soit la matrice donnée ci-dessous, calculez la somme des éléments de chaque ligne et
de chaque colonne en utilisant la méthode numpy.sum()

MS = [[20, 12, 4, 45, 37, 29, 28], [11, 3, 44, 36, 35, 27, 19], [2, 43, 42, 34, 26, 18, 10],
[49, 41, 33, 25, 17, 9, 1], [40, 32, 24, 16, 8, 7, 48], [31, 23, 15, 14, 6, 47, 39], [22, 21, 13,
5, 46, 38, 30]]

In [70]:
import numpy as np

MS = np.array([
    [20, 12, 4, 45, 37, 29, 28],
    [11, 3, 44, 36, 35, 27, 19],
    [2, 43, 42, 34, 26, 18, 10],
    [49, 41, 33, 25, 17, 9, 1],
    [40, 32, 24, 16, 8, 7, 48],
    [31, 23, 15, 14, 6, 47, 39],
    [22, 21, 13, 5, 46, 38, 30]
])


print(MS.sum(axis=0))
print(MS.sum(axis=1))

[175 175 175 175 175 175 175]
[175 175 175 175 175 175 175]


### 4

Générez une matrice de dimensions 10x10 contenant des valeurs aléatoires entre -1.0
et 1.0. Calculez la valeur maximale, minimale et moyenne. Calculez la position où se
trouve la valeur maximale et minimale (argmax et argmin) et la position du minimum par
ligne (axis=1).

In [35]:
import numpy as np

matrix = np.random.uniform(-1.0, 1.0, (10, 10))

min = matrix.min()
posMin = matrix.argmin()

max = matrix.max()
posMax = matrix.argmax()

avg = matrix.mean()

minPerLine = matrix.min(axis=1)

print(f"Minimum: {min} at position {posMin}")
print(f"Maximum: {max} at position {posMax}")
print(f"Average: {avg}")
print(f"Min per line: {minPerLine}")
# print(matrix)

Minimum: -0.9847552971721352 at position 76
Maximum: 0.9929867065836104 at position 24
Average: 0.007970028802058686
Min per line: [-0.95586058 -0.63390562 -0.95883632 -0.90580681 -0.97794245 -0.91001776
 -0.83381417 -0.9847553  -0.7464368  -0.56909237]


### 5

Créez une matrice x de dimensions 10x10 contenant des valeurs aléatoires entre 0.0 et
1.0 et calculez le carré de chaque élément. Comparez le temps de calcul (p.ex. utilisez
la magic command %%timeit) d’une implémentation qui utilise une double boucle for et
une implémentation qui fait le calcul demandé tout simplement ainsi : x = x ** 2

In [75]:
import numpy as np

matrix = np.random.uniform(0.0, 1.0, (10, 10))

s1 = np.array(matrix)
print("** 2")
s1 = %timeit s1 ** 2

s2 = np.array(matrix)
def square(m):
    for i in range(len(m)):
        for j in range(len(m[i])):
            m[i][j] = m[i][j] ** 2
    return m

print("2 loops")
%timeit square(s2)


** 2
529 ns ± 1.29 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2 loops
55.9 µs ± 518 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 6

Créez un array de dimension 100 avec des valeurs aléatoires entre 0 et 1.0 et générez
un nouvel array où les éléments plus petits que 0.5 sont élevées au carré. Comparez le
temps de calcul a) d’une implémentation à l’aide d’une boucle for, b) d’une
implémentation qui utilise la méthode np.where(), et c) d’une implémentation à travers
des masques.

In [84]:
import numpy as np

a = np.random.uniform(0.0, 1.0, 100)

a

# TODO here

array([0.07649072, 0.78849698, 0.29293275, 0.99322752, 0.65762324,
       0.11815821, 0.1234452 , 0.88826396, 0.75559392, 0.03570249,
       0.29413459, 0.14347335, 0.48271339, 0.5822072 , 0.07150313,
       0.02646819, 0.28155397, 0.41994181, 0.87719812, 0.35662121,
       0.04833029, 0.77528578, 0.09169046, 0.71369942, 0.62167006,
       0.41351228, 0.58454727, 0.73529002, 0.8488753 , 0.37999527,
       0.7422683 , 0.1731183 , 0.3982632 , 0.16035426, 0.19482866,
       0.68662674, 0.6731996 , 0.93059808, 0.95235756, 0.34996153,
       0.39811553, 0.60714489, 0.99615077, 0.25673728, 0.58526491,
       0.72231451, 0.19178779, 0.17291927, 0.71241857, 0.01160306,
       0.35569874, 0.31901374, 0.68811336, 0.98046931, 0.07851648,
       0.1169586 , 0.43957693, 0.16459645, 0.22127291, 0.52396189,
       0.27462641, 0.56883883, 0.00593826, 0.49870403, 0.8255304 ,
       0.80401366, 0.49936597, 0.86634282, 0.25227132, 0.57370974,
       0.12245299, 0.6450141 , 0.57425167, 0.77836466, 0.28885

## Exercices Matplotlib

### 7

Générez un graphique de la fonction tangente hyperbolique définie par :

tanh(x) = (1 - exp(-2 * x)) / (1 + exp(-2 * x)), pour -5 < x < 5

Ajouter un titre, des labels et une grille